### ISSUE TITLE
Formatter preferences (Flake8, Black, etc.)

### ISSUE THREAD

**Issue by Zulko** [Global-Biofoundries-Alliance/SynBioPython#4]
Would be nice to enforce formatting using e.g. Black (which seems to be very popular). I'm think there  are some ways to check/correct PEP8 and other formatting errors at commit time but I've never done it.

**Comment by zoltuz** [comment]
I also have limited experience with formatting rules, but they are really helpful in the long run. Here's an article which offers the latest tools.  I try to follow in my projects, but not all of them. 
https://medium.com/georgian-impact-blog/python-tooling-makes-a-project-tick-181d567eea44

**Comment by yeohjingwui** [comment]
I found this link which I think would be useful for us. They showed how to use precommit to include black and flake8 
[https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/](url)

**Comment by neilswainston** [comment]
Adopted both black and flake8.
